[package]
name = "linux_creation_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = {package = "gtk4", version = "0.4.8"}
reqwest = { version = "0.10"}
tokio = { version = "0.2", features = ["full"] }
bytes = "^1.0"
